export const leaders = [
  { id: "lincoln", name: "Abraham Lincoln", price: 5, wikiTitle: "Abraham_Lincoln" },
  { id: "fdr", name: "Franklin D. Roosevelt", price: 5, wikiTitle: "Franklin_D._Roosevelt" },
  { id: "alexander", name: "Alexander the Great", price: 5, wikiTitle: "Alexander_the_Great" },
  { id: "mandela", name: "Nelson Mandela", price: 5, wikiTitle: "Nelson_Mandela" },
  { id: "lee-kuan-yew", name: "Lee Kuan Yew", price: 5, wikiTitle: "Lee_Kuan_Yew" },
  { id: "gandhi", name: "Mahatma Gandhi", price: 4, wikiTitle: "Mahatma_Gandhi" },
  { id: "ataturk", name: "Mustafa Kemal Atatürk", price: 4, wikiTitle: "Mustafa_Kemal_Atatürk" },
  { id: "churchill", name: "Winston Churchill", price: 4, wikiTitle: "Winston_Churchill" },
  { id: "caesar", name: "Julius Caesar", price: 4, wikiTitle: "Julius_Caesar" },
  { id: "marcus-aurelius", name: "Marcus Aurelius", price: 4, wikiTitle: "Marcus_Aurelius" },
  { id: "napoleon", name: "Napoleon Bonaparte", price: 3, wikiTitle: "Napoleon" },
  { id: "genghis", name: "Genghis Khan", price: 3, wikiTitle: "Genghis_Khan" },
  { id: "elizabeth-i", name: "Elizabeth I", price: 3, wikiTitle: "Elizabeth_I" },
  { id: "thatcher", name: "Margaret Thatcher", price: 3, wikiTitle: "Margaret_Thatcher" },
  { id: "bismarck", name: "Otto von Bismarck", price: 3, wikiTitle: "Otto_von_Bismarck" },
  { id: "cleopatra", name: "Cleopatra VII", price: 2, wikiTitle: "Cleopatra" },
  { id: "henry-viii", name: "Henry VIII", price: 2, wikiTitle: "Henry_VIII" },
  { id: "jfk", name: "John F. Kennedy", price: 2, wikiTitle: "John_F._Kennedy" },
  { id: "mao", name: "Mao Zedong", price: 2, wikiTitle: "Mao_Zedong" },
  { id: "trump", name: "Donald Trump", price: 2, wikiTitle: "Donald_Trump" },
  { id: "hitler", name: "Adolf Hitler", price: 1, wikiTitle: "Adolf_Hitler" },
  { id: "stalin", name: "Joseph Stalin", price: 1, wikiTitle: "Joseph_Stalin" },
  { id: "saddam", name: "Saddam Hussein", price: 1, wikiTitle: "Saddam_Hussein" },
  { id: "pol-pot", name: "Pol Pot", price: 1, wikiTitle: "Pol_Pot" },
  { id: "putin", name: "Vladimir Putin", price: 1, wikiTitle: "Vladimir_Putin" },
];

export const tiers = [5, 4, 3, 2, 1];
